export const products = [
  {
    id: "1",
    name: "Laser Lemonade Machine",
    status: "Draft",
    price: "$499.99",
    quantity: 25,
    date: "2023-07-12 10:42 AM",
    image: "/images/product/lemonade.jpg",
  },
  {
    id: "2",
    name: "Hypernova Headphones",
    status: "Active",
    price: "$129.99",
    quantity: 100,
    date: "2023-10-18 03:21 PM",
    image: "/images/product/headphones.jpg",
  },
  {
    id: "3",
    name: "AeroGlow Desk Lamp",
    status: "Active",
    price: "$39.99",
    quantity: 50,
    date: "2023-11-29 08:15 AM",
    image: "/images/product/lamp.jpg",
  },
  {
    id: "4",
    name: "TechTonic Energy Drink",
    status: "Draft",
    price: "$2.99",
    quantity: 0,
    date: "2023-12-25 11:59 PM",
    image: "/images/product/redbull.jpg",
  },
  {
    id: "5",
    name: "Gamer Gear Pro Controller",
    status: "Active",
    price: "$59.99",
    quantity: 75,
    date: "2024-01-01 12:00 AM",
    image: "/images/product/controller.jpg",
  },
  {
    id: "6",
    name: "Luminous VR Headset",
    status: "Active",
    price: "$199.99",
    quantity: 30,
    date: "2024-02-14 02:14 PM",
    image: "/images/product/mic.jpg",
  },
];