import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Mail,
  Cast,
  Radio,
  type Icon as LucideIcon,
} from "lucide-react";
import GithubIcon from "./github-icon";
import DashboardIcon from "./dashboard-icon";

export type Icon = typeof LucideIcon;

export const Icons = {
  logo: Radio,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  mail: Mail,
  google: Pizza,
  twitter: Twitter,
  check: Check,
  gitHub: GithubIcon,
  dashboardIcon: DashboardIcon,
};
